### ISSUE TITLE
Links broken on assignments/project.html (and possibly other pages)

### ISSUE THREAD

**Issue by wardbradt** [nzufelt/open_source_movement_csc630#102]
If one visits https://nzufelt.github.io/open_source_movement_csc630/assignments/Project.html, the "assignments," "resources," "git cheatsheet," "essays" and "projects" links are broken. I presume this is because they redirect to an assignments/ URL. For example, clicking on the "Resources" link redirects to https://nzufelt.github.io/open_source_movement_csc630/assignments/resources.html. I believe it should redirect to https://nzufelt.github.io/open_source_movement_csc630/resources.html.

**Comment by milesmcc** [comment]
The css is broken too

**Comment by ruddfawcett** [comment]
Would be great if you could open a PR! 😍
