### ISSUE TITLE
Styling the website... CSS or SCSS?

### ISSUE THREAD

**Issue by ruddfawcett** [nzufelt/open_source_movement_csc630#3]
Are people thinking that we should use CSS or SCSS for styling this website? Or maybe we start out with some vanilla CSS to start and then move to a preprocessor at a later stage?

**Comment by nzufelt** [comment]
My vote is for CSS, so that people that are a bit newer to webdev can have more things to tackle.

**Comment by milesmcc** [comment]
For simplicity, we *could* also use Jekyll+Markdown and use the built-in GitHub themes, which are quite [nice](https://pages.github.com/themes/) ([see also](https://pages-themes.github.io/minimal/)).

This approach has the added advantage(?) of using Markdown as opposed to HTML, which further decreases the knowledge barrier to entry.

**Comment by ruddfawcett** [comment]
Sounds good!

**Comment by ruddfawcett** [comment]
@milesmcc how will we practice our HTML and CSS then? 😉

**Comment by milesmcc** [comment]
@ruddfawcett in our own projects :)

It's perhaps also worth noting that HTML can be embedded into Jekyll markdown files for more complex pages, if needed. We won't be *completely* without HTML.

**Comment by ruddfawcett** [comment]
@milesmcc fair enough! Closing this now as @nzufelt answered CSS vs. SCSS question, but perhaps Jekyll could be opened in another issue.
