### ISSUE TITLE
Adding to CONTRIBUTING.md

### ISSUE THREAD

**Issue by kabirnagral** [nzufelt/open_source_movement_csc630#58]
I think that we should add stuff to the CONTRIBUTING.md file. Any thoughts or ideas on what should go in it?

**Comment by sam-xif** [comment]
Yes, I will be adding standards on how to submit essays and other assets so that the pull requests are all the same and are able to be merged more easily. Let me know if you have any other suggestions.

**Comment by ruddfawcett** [comment]
Thanks, @sam-xif and @kabirnagral!
