### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by milesmcc** [nzufelt/open_source_movement_csc630#6]
How should we license the repository? My vote is for [GPLv3](https://www.gnu.org/licenses/gpl-3.0.en.html).

*To learn more about open-source software licensing, check out [this](https://www.toptal.com/open-source/developers-guide-to-open-source-licenses) helpful guide.*

**Comment by nzufelt** [comment]
> To learn more about open-source software licensing, check out [this](https://www.toptal.com/open-source/developers-guide-to-open-source-licenses) helpful guide.

Sounds like a great resource to add to the discussion for #5.

**Comment by milesmcc** [comment]
If we hold a repository review conversation on Monday, perhaps we should as a class come to a decision, as people shouldn't contribute to repositories without licenses (we don't want their work to be misused, after all!).

**Comment by nzufelt** [comment]
Fixed by [this commit](https://github.com/nzufelt/open_source_movement_csc630/commit/7276d0e81a8a0ea1e46e6835234295bdfcc39416).
